/**
 ▄█        ▄██████▄     ▄████████   ▄▄▄▄███▄▄▄▄      ▄████████    ▄████████ 
███       ███    ███   ███    ███ ▄██▀▀▀███▀▀▀██▄   ███    ███   ███    ███ 
███       ███    ███   ███    ███ ███   ███   ███   ███    ███   ███    █▀  
███       ███    ███  ▄███▄▄▄▄██▀ ███   ███   ███   ███    ███   ███        
███       ███    ███ ▀▀███▀▀▀▀▀   ███   ███   ███ ▀███████████ ▀███████████ 
███       ███    ███ ▀███████████ ███   ███   ███   ███    ███          ███ 
███▌    ▄ ███    ███   ███    ███ ███   ███   ███   ███    ███    ▄█    ███ 
█████▄▄██  ▀██████▀    ███    ███  ▀█   ███   █▀    ███    █▀   ▄████████▀  
▀                      ███    ███                                           
 * Code generated by Lormas Bot Lab
 * All code in this folder belongs to Lormas Bot Lab
 * For any rights, contact support@lormas.net
*/

import type { HexColorString } from 'discord.js';
import * as dotenv from 'dotenv';
dotenv.config();

const config = {
	token: process.env.TOKEN,
	prefix: ['lbl.'],
	developers: ['926643835419910184', '921368997482602536'],
	mainGuildId: '1334534198941192272',
	updateChannelId: '1334534198941192275'
}

export default config;