/**
 ▄█        ▄██████▄     ▄████████   ▄▄▄▄███▄▄▄▄      ▄████████    ▄████████ 
███       ███    ███   ███    ███ ▄██▀▀▀███▀▀▀██▄   ███    ███   ███    ███ 
███       ███    ███   ███    ███ ███   ███   ███   ███    ███   ███    █▀  
███       ███    ███  ▄███▄▄▄▄██▀ ███   ███   ███   ███    ███   ███        
███       ███    ███ ▀▀███▀▀▀▀▀   ███   ███   ███ ▀███████████ ▀███████████ 
███       ███    ███ ▀███████████ ███   ███   ███   ███    ███          ███ 
███▌    ▄ ███    ███   ███    ███ ███   ███   ███   ███    ███    ▄█    ███ 
█████▄▄██  ▀██████▀    ███    ███  ▀█   ███   █▀    ███    █▀   ▄████████▀  
▀                      ███    ███                                           
 * Code generated by Lormas Bot Lab
 * All code in this folder belongs to Lormas Bot Lab
 * For any rights, contact support@lormas.net
*/

import type config from './config';
import type Keyv from 'keyv';

declare module 'discord.js' {
    interface Client {
        _config: typeof config,
    }
}